
package com.janpix.repodoc.porttype;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-10-14T22:29:45.974-03:00
 * Generated source version: 2.7.2
 * 
 */
public final class RepositorioJanpixService_RepositorioJanpixServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://repodoc.janpix.com/", "RepositorioJanpixServiceService");

    private RepositorioJanpixService_RepositorioJanpixServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RepositorioJanpixServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RepositorioJanpixServiceService ss = new RepositorioJanpixServiceService(wsdlURL, SERVICE_NAME);
        RepositorioJanpixService port = ss.getRepositorioJanpixServicePort();  
        
        {
        System.out.println("Invoking retrieveDocument...");
        com.janpix.repodoc.porttype.RetrieveDocumentRequest _retrieveDocument_retrieveDocumentMessage = null;
        com.janpix.repodoc.porttype.AckMessage _retrieveDocument__return = port.retrieveDocument(_retrieveDocument_retrieveDocumentMessage);
        System.out.println("retrieveDocument.result=" + _retrieveDocument__return);


        }
        {
        System.out.println("Invoking provideAndRegisterDocument...");
        com.janpix.repodoc.porttype.ProvideAndRegisterDocumentRequest _provideAndRegisterDocument_provideAndRegisterDocumentMessage = null;
        com.janpix.repodoc.porttype.AckMessage _provideAndRegisterDocument__return = port.provideAndRegisterDocument(_provideAndRegisterDocument_provideAndRegisterDocumentMessage);
        System.out.println("provideAndRegisterDocument.result=" + _provideAndRegisterDocument__return);


        }

        System.exit(0);
    }

}
