package com.janpix.repodoc.porttype;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-10-14T22:29:46.046-03:00
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "http://repodoc.janpix.com/", name = "RepositorioJanpixService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RepositorioJanpixService {

    @WebResult(name = "retrieveDocumentResponse", targetNamespace = "http://repodoc.janpix.com/", partName = "retrieveDocumentResponse")
    @WebMethod
    public AckMessage retrieveDocument(
        @WebParam(partName = "retrieveDocumentMessage", name = "retrieveDocumentMessage", targetNamespace = "http://repodoc.janpix.com/")
        RetrieveDocumentRequest retrieveDocumentMessage
    );

    @WebResult(name = "provideAndRegisterDocumentResponse", targetNamespace = "http://repodoc.janpix.com/", partName = "provideAndRegisterDocumentResponse")
    @WebMethod
    public AckMessage provideAndRegisterDocument(
        @WebParam(partName = "provideAndRegisterDocumentMessage", name = "provideAndRegisterDocumentMessage", targetNamespace = "http://repodoc.janpix.com/")
        ProvideAndRegisterDocumentRequest provideAndRegisterDocumentMessage
    );
}
