package com.janpix.webclient.regdoc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.soap.MTOM;

import com.janpix.servidordocumentos.dto.message.ACKMessage;
import com.janpix.servidordocumentos.dto.message.ACKStoredQueryMessage;
import com.janpix.servidordocumentos.dto.message.QueryDocumentRequest;
import com.janpix.servidordocumentos.dto.message.RegisterDocumentRequest;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-10-30T08:48:02.127-03:00
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "http://services.regdoc.janpix.com/", name = "DocumentJanpixService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@MTOM(enabled =  true)
public interface DocumentJanpixService {

    @WebResult(name = "queryDocumentResponse", targetNamespace = "http://services.regdoc.janpix.com/", partName = "queryDocumentResponse")
    @WebMethod
    public ACKStoredQueryMessage queryDocument(
        @WebParam(partName = "queryDocumentRequestMessage", name = "queryDocumentRequestMessage", targetNamespace = "http://services.regdoc.janpix.com/")
        QueryDocumentRequest queryDocumentRequestMessage
    );

    @WebResult(name = "registerDocumentResponse", targetNamespace = "http://services.regdoc.janpix.com/", partName = "registerDocumentResponse")
    @WebMethod
    public ACKMessage registerDocument(
        @WebParam(partName = "registerDocumentRequestMessage", name = "registerDocumentRequestMessage", targetNamespace = "http://services.regdoc.janpix.com/")
        RegisterDocumentRequest registerDocumentRequestMessage
    );
}
