package com.janpix.repodoc.porttype;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import com.janpix.servidordocumentos.dto.message.ACKMessage;
import com.janpix.servidordocumentos.dto.message.ProvideAndRegisterDocumentRequest;
import com.janpix.servidordocumentos.dto.message.RetrieveDocumentRequest;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-10-14T22:29:46.046-03:00
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "http://repodoc.janpix.com/", name = "RepositorioJanpixService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RepositorioJanpixServicePortType {

    @WebResult(name = "provideAndRegisterDocumentResponse", targetNamespace = "http://repodoc.janpix.com/", partName = "provideAndRegisterDocumentResponse")
    @WebMethod
    public ACKMessage provideAndRegisterDocument(
        @WebParam(partName = "provideAndRegisterDocumentMessage", name = "provideAndRegisterDocumentMessage", targetNamespace = "http://repodoc.janpix.com/")
        ProvideAndRegisterDocumentRequest provideAndRegisterDocumentMessage
    );
    
    @WebResult(name = "retrieveDocumentResponse", targetNamespace = "http://repodoc.janpix.com/", partName = "retrieveDocumentResponse")
    @WebMethod
    public ACKMessage retrieveDocument(
        @WebParam(partName = "retrieveDocumentMessage", name = "retrieveDocumentMessage", targetNamespace = "http://repodoc.janpix.com/")
        RetrieveDocumentRequest retrieveDocumentMessage
    );


}
